/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9831fb87-0756-4d62-b29d-bd9954179122",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_v87T98xwb",
    "aws_user_pools_web_client_id": "6i44p0ugdind97bulh46lgutfl",
    "oauth": {
        "domain": "audimorpha43c2c47-a43c2c47-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/sign-in/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
